galaxy_info:
  author: Nestor G Pestelos Jr
  description: Installs MySQL
  license: MIT
  min_ansible_version: 1.9
  platforms:
  - name: Ubuntu
    versions:
    - 14.04
  galaxy_tags:
    - development
    - databases
dependencies: []